apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - custom/service.yaml
  - custom/deployment.yaml
  - custom/http-route.yaml
components:
  - ../../components/core
