apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
spec:
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
        - name: APP_NAME
          ports:
            - containerPort: $${{ アプリケーションが待ち受けているポート }}
