apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: APP_NAME
spec:
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: $${{ アプリケーションをルーティングするパス }}
      backendRefs:
        - name: APP_NAME
          port: $${{ アプリケーションが待ち受けているポート }}
