apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
    service: APP_NAME
spec:
  ports:
  selector:
    app: APP_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP_NAME
      version: v1
  template:
    metadata:
      labels:
        app: APP_NAME
        version: v1
    spec:
      serviceAccountName: APP_NAME
      containers:
        - name: APP_NAME
          image: registry
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-config
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: APP_NAME
spec:
  hostnames:
    - "*"
